### ISSUE TITLE
incomplete install

### ISSUE THREAD

**Issue by jasedwards** [johannesjo/generator-modular-angular#1]
Hi, I ran npm install -g generator-moda but the only thing installed was a node_modules folder and the app folder.  

![image](https://cloud.githubusercontent.com/assets/5818023/6992200/6c58f7f2-da85-11e4-985c-63fcdb7faeac.png)

**Comment by johannesjo** [comment]
Thank you very much for reporting. I wasn't aware that you explicitly need to declare the included files inside the package.json for modules published to npm. This should be fixed with the latest version. Thanks again!
