### ISSUE TITLE
Generator removes manual additions of scripts on inject

### ISSUE THREAD

**Issue by 34r7h** [johannesjo/generator-modular-angular#14]
Hi Johannes, I bower installed I want to inject a template.js file from Foundation-for-apps but each time gulp serve runs, it removes the `<script src="bower_components/foundation-apps/dist/js/foundation-apps-templates.js"></script>` that was manually added.

Is this a bug or should I be doing something different to get the right behaviour?

here's the repo if it helps https://github.com/irthos/medviz

Many thanks!

**Comment by johannesjo** [comment]
Hello irthos. Thanks for reporting! That's the correct behaviour if you place your `<script>` between the `<!-- bower:js -->` or `<!-- endbower -->`. Same goes for  `<!-- inject:js -->` and `<!-- endinject -->`.

**Comment by 34r7h** [comment]
ok my oversight. many thanks!
