### ISSUE TITLE
Experimental: ES6 and/or TypeScript

### ISSUE THREAD

**Issue by 34r7h** [johannesjo/generator-modular-angular#20]
Hi Johannes, would you point out where in the gulp dev file to add transpilers? I'd like to add inject the es6 files at runtime via babel after hacking the templates a bit. Cheers!

**Comment by johannesjo** [comment]
Hello, sorry for not getting back to you earlier. I would probably add them to the dev.js as well as to the build.js.

**Comment by 34r7h** [comment]
Thanks, Johannes
