### ISSUE TITLE
PhantomJS Error on Running

### ISSUE THREAD

**Issue by bdenham** [johannesjo/generator-modular-angular#21]
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: angular
  at /Users/bruce/app/scripts/_app.js:13

**Comment by johannesjo** [comment]
Thanks for reporting! Probably should work once you run the generator again.

**Comment by johannesjo** [comment]
Should be fixed! Thanks again for reporting!
